name: cel
channels:
  - conda-forge
dependencies:
  - python=3.11
  - pip
  - jupyter
  - ipykernel
  - python-dotenv
  - tqdm
  - ipympl
  - matplotlib
  - seaborn
  - dill
  - diskcache
  - pip:
      - "-e .[test]"
